### ISSUE TITLE
PLUGIN MI SIE PALi!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by XYZ-RGB** [iNyatix/NT-WrongNickname#1]
PLUGIN MI SIE PALI POMOCY!!!!
![image](https://user-images.githubusercontent.com/58667753/96362868-ccfa7300-1130-11eb-8f36-bfc68f809798.png)

**Comment by iNyatix** [comment]
wloz do ryzu

**Comment by XYZ-RGB** [comment]
teraz sje mocniej pali, nawet komentaa _/tps_ nje dzial;a!!!!!!!!!!!!!!!!!!!!
